<div class="card card-danger">
    <div class="card-header">
        <h3 class="card-title">Produtos por categoria</h3>
    </div>
    <div class="card-body">
        <div class="chartjs-size-monitor">
            <div class="chartjs-size-monitor-expand">
                <div class=""></div>
            </div>
            <div class="chartjs-size-monitor-shrink">
                <div class=""></div>
            </div>
        </div>
        <canvas id="pieChart"
            style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%; display: block; width: 334px;"
            width="334" height="250" class="chartjs-render-monitor"></canvas>
    </div>
    <!-- /.card-body -->
</div>

<div class="card card-danger">
    <div class="card-header">
        <h3 class="card-title">Produtos por fornecedor</h3>
    </div>
    <div class="card-body">
        <div class="chartjs-size-monitor">
            <div class="chartjs-size-monitor-expand">
                <div class=""></div>
            </div>
            <div class="chartjs-size-monitor-shrink">
                <div class=""></div>
            </div>
        </div>
        <canvas id="pieChart2"
            style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%; display: block; width: 334px;"
            width="334" height="250" class="chartjs-render-monitor"></canvas>
    </div>
    <!-- /.card-body -->
</div>

<script>
    $(function () {

        var donutData = {
            labels: [
                <?php foreach($this->view->productsByCategory as $key => $productsByCategory){ ?>
                    '<?= $productsByCategory['nome'] ?>',
                <?php } ?>
            ],
            datasets: [{
                data: [
                    <?php foreach($this->view->productsByCategory as $key => $productsByCategory){ ?>
                        '<?= $productsByCategory['total_produtos'] ?>',
                    <?php } ?>
                ],
                backgroundColor: ['#f56954', '#00a65a', '#f39c12', '#00c0ef', /*'#3c8dbc', '#d2d6de'*/],
            }]
        }

        var donutData2 = {
            labels: [
                <?php foreach($this->view->productsByProvider as $key => $productsByProvider){ ?>
                    '<?= $productsByProvider['nome'] ?>',
                <?php } ?>
            ],
            datasets: [{
                data: [
                    <?php foreach($this->view->productsByProvider as $key => $productsByProvider){ ?>
                        '<?= $productsByProvider['total_produtos'] ?>',
                    <?php } ?>
                ],
                backgroundColor: ['#f56954', '#00a65a', '#f39c12', '#00c0ef', '#3c8dbc', '#d2d6de', '#ff66d9', '#88ff4d'],
            }]
        }

        //-------------
        //- PIE CHART -
        //-------------
        // Get context with jQuery - using jQuery's .get() method.
        var pieChartCanvas = $('#pieChart').get(0).getContext('2d')
        var pieData = donutData;
        var pieOptions = {
            maintainAspectRatio: false,
            responsive: true,
        }

        var pieChartCanvas2 = $('#pieChart2').get(0).getContext('2d')
        var pieData2 = donutData2;
        var pieOptions2 = {
            maintainAspectRatio: false,
            responsive: true,
        }

        //Create pie or douhnut chart
        // You can switch between pie and douhnut using the method below.
        new Chart(pieChartCanvas, {
            type: 'pie',
            data: pieData,
            options: pieOptions
        })

        new Chart(pieChartCanvas2, {
            type: 'pie',
            data: pieData2,
            options: pieOptions2
        })

    })
</script>