<?php if(isset($_GET['save']) && $_GET['save'] == 1){ ?>
    <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h5><i class="icon fas fa-check"></i> Sucesso!</h5>
        Produto cadastrado com sucesso.
    </div>
<?php } ?>

<?php if(isset($_GET['save']) && $_GET['save'] == 2){ ?>
    <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h5><i class="icon fas fa-check"></i> Erro!</h5>
        Erro ao cadastra produto.
    </div>
<?php } ?>

<div class="card card-primary">
    <div class="card-header">
        <h4>Cadastro Produto</h4>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form action="/produto/save" method="post">
        <div class="card-body">

            <div class="form-group">
                <label for="exampleInputNome">Nome</label>
                <input type="text" name="nome" class="form-control" id="exampleInputNome" placeholder="Enter nome"
                    required maxlength="50">
            </div>

            <div class="form-group">
                <label for="exampleInputValorCompra">Valor de compra</label>
                <input type="number" name="valor_compra" class="form-control" id="exampleInputValorCompra" placeholder="Enter valor de compra"
                    required min="1" max="1000">
            </div>

            <div class="form-group">
                <label for="exampleInputValorVenda">Valor de venda</label>
                <input type="number" name="valor_venda" class="form-control" id="exampleInputValorVenda" placeholder="Enter valor de venda"
                    required min="1" max="1000">
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Comissão</label>
                <input type="number" name="comissao" class="form-control" id="exampleInputComissao"
                    placeholder="Enter comissão" required min="0" max="1000">
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Quantidade</label>
                <input type="number" name="quantidade" class="form-control" id="exampleInputQuantidade"
                    placeholder="Enter quantidade" required min="0" max="1000">
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Fornecedor</label>

                <select class="form-control" name="fornecedor" id="exampleSelectFornecedor">
                    <?php foreach($this->view->dados as $i => $dado){ ?>
                        <?php if($i == 'fornecedores'){ ?>
                            <?php foreach($dado as $j => $fornecedor){ ?>
                                <option value="<?= $fornecedor['id'] ?>"><?= $fornecedor['nome'] ?></option>
                            <?php } ?>
                        <?php } ?>
                    <?php } ?>
                </select>

            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Categoria</label>
                <select class="form-control" name="categoria" id="exampleSelectCategoria">
                    <?php foreach($this->view->dados as $i => $dado){ ?>
                        <?php if($i == 'categorias'){ ?>
                            <?php foreach($dado as $j => $categoria){ ?>
                                <option value="<?= $categoria['id'] ?>"><?= $categoria['nome'] ?></option>
                            <?php } ?>
                        <?php } ?>
                    <?php } ?>
                </select>
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Data de validade</label>
                <input type="date" name="data_validade" class="form-control" id="exampleInputData">
            </div>

        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
    </form>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title"></h3>

                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <!-- /.card-header -->
            <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nome</th>
                            <th>Valor de compra</th>
                            <th>Valor de venda</th>
                            <th>Comissão</th>
                            <th>Quantidade</th>
                            <th>Fornecedor</th>
                            <th>Categoria</th>
                            <th>Data de validade</th>
                            <th>Status</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>

                        <?php foreach($this->view->dados as $i => $dado){ ?>
                            <?php if($i == 'produtos'){ ?>
                                <?php foreach($dado as $j => $produto){ ?>
                                    <tr>
                                        <td><?= $produto['id'] ?></td>
                                        <td><?= $produto['nome'] ?></td>
                                        <td><?= $produto['valor_compra'] ?></td>
                                        <td><?= $produto['valor_venda'] ?></td>
                                        <td><?= $produto['comissao'] ?></td>
                                        <td><?= $produto['qtd'] ?></td>
                                        <td><?= $produto['id_fornecedor'] ?></td>
                                        <td><?= $produto['id_categoria'] ?></td>
                                        <td><?= $produto['data_validade'] ?></td>
                                        <td><?= $produto['id_status'] ?></td>
                                        <td><i class="fas fa-trash text-danger" onclick="deletar(<?= $produto['id'] ?>)"></i></td>
                                        <td><i class="fas fa-edit text-info"></i></td>
                                    </tr>
                                <?php } ?>
                            <?php } ?>
                        <?php } ?>

                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->

        </div>
        <!-- /.card -->
    </div>
</div>

<script>
    function deletar(id){
        location.href = '/produto/deletar?id=' + id;
    }
</script>
