<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title"></h3>

                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <?php if(isset($_GET['deletar']) && $_GET['deletar'] == 1){ ?>
                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h5><i class="icon fas fa-check"></i> Sucesso!</h5>
                    Produto excluido com sucesso.
                </div>
            <?php } ?>

            <?php if(isset($_GET['deletar']) && $_GET['deletar'] == 2) { ?>
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h5><i class="icon fas fa-check"></i> Erro!</h5>
                    Erro ao excluir produto.
                </div>
            <?php } ?>

            <!-- /.card-header -->
            <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nome</th>
                            <th>Valor de compra</th>
                            <th>Valor de venda</th>
                            <th>Comissão</th>
                            <th>Quantidade</th>
                            <th>Fornecedor</th>
                            <th>Categoria</th>
                            <th>Data de validade</th>
                            <th>Status</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>

                        <?php foreach($this->view->dados as $i => $dado){ ?>
                            <?php if($i == 'produtos'){ ?>
                                <?php foreach($dado as $j => $produto){ ?>
                                    <tr>
                                        <td><?= $produto['id'] ?></td>
                                        <td><?= $produto['nome'] ?></td>
                                        <td><?= $produto['valor_compra'] ?></td>
                                        <td><?= $produto['valor_venda'] ?></td>
                                        <td><?= $produto['comissao'] ?></td>
                                        <td><?= $produto['qtd'] ?></td>
                                        <td><?= $produto['id_fornecedor'] ?></td>
                                        <td><?= $produto['id_categoria'] ?></td>
                                        <td><?= $produto['data_validade'] ?></td>
                                        <td><?= $produto['id_status'] ?></td>
                                        <td><i class="fas fa-trash text-danger" onclick="deletar(<?= $produto['id'] ?>)"></i></td>
                                        <td><i class="fas fa-edit text-info"></i></td>
                                    </tr>
                                <?php } ?>
                            <?php } ?>
                        <?php } ?>

                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->

        </div>
        <!-- /.card -->
    </div>
</div>

<script>
    function deletar(id){
        location.href = '/produto/deletar?id=' + id;
    }
</script>
