<?php if(isset($_GET['save']) && $_GET['save'] == 1){ ?>
    <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h5><i class="icon fas fa-check"></i> Sucesso!</h5>
        Produto cadastrado com sucesso.
    </div>
<?php } ?>

<?php if(isset($_GET['save']) && $_GET['save'] == 2){ ?>
    <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h5><i class="icon fas fa-check"></i> Erro!</h5>
        Erro ao cadastra produto.
    </div>
<?php } ?>

<div class="card card-primary">
    <div class="card-header">
        <h4>Cadastro Produto</h4>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form action="/produto/save" method="post">
        <div class="card-body">

            <div class="form-group">
                <label for="exampleInputNome">Nome</label>
                <input type="text" name="nome" class="form-control" id="exampleInputNome" placeholder="Enter nome"
                    required maxlength="50">
            </div>

            <div class="form-group">
                <label for="exampleInputValorCompra">Valor de compra</label>
                <input type="number" name="valor_compra" class="form-control" id="exampleInputValorCompra" placeholder="Enter valor de compra"
                    required min="1" max="1000">
            </div>

            <div class="form-group">
                <label for="exampleInputValorVenda">Valor de venda</label>
                <input type="number" name="valor_venda" class="form-control" id="exampleInputValorVenda" placeholder="Enter valor de venda"
                    required min="1" max="1000">
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Comissão</label>
                <input type="number" name="comissao" class="form-control" id="exampleInputComissao"
                    placeholder="Enter comissão" required min="0" max="1000">
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Quantidade</label>
                <input type="number" name="quantidade" class="form-control" id="exampleInputQuantidade"
                    placeholder="Enter quantidade" required min="0" max="1000">
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Fornecedor</label>

                <select class="form-control" name="fornecedor" id="exampleSelectFornecedor">
                    <option value=""></option>
                    <?php foreach($this->view->dados as $i => $dado){ ?>
                        <?php if($i == 'fornecedores'){ ?>
                            <?php foreach($dado as $j => $fornecedor){ ?>
                                <option value="<?= $fornecedor['id'] ?>"><?= $fornecedor['nome'] ?></option>
                            <?php } ?>
                        <?php } ?>
                    <?php } ?>
                </select>

            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Categoria</label>
                <select class="form-control" name="categoria" id="exampleSelectCategoria">
                    <option value=""></option>
                    <?php foreach($this->view->dados as $i => $dado){ ?>
                        <?php if($i == 'categorias'){ ?>
                            <?php foreach($dado as $j => $categoria){ ?>
                                <option value="<?= $categoria['id'] ?>"><?= $categoria['nome'] ?></option>
                            <?php } ?>
                        <?php } ?>
                    <?php } ?>
                </select>
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Data de validade</label>
                <input type="date" name="data_validade" class="form-control" id="exampleInputData">
            </div>

        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
    </form>
</div>