<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title"></h3>

                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <!-- /.card-header -->
            <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nome</th>
                            <th>Telefone</th>
                            <th>CPF</th>
                            <th>E-mail</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->view->dados as $key => $collaborator){ ?>
                            <tr>
                                <td><?= $collaborator['id'] ?></td>
                                <td><?= $collaborator['nome_completo'] ?></td>
                                <td><?= $collaborator['telefone'] ?></td>
                                <td><?= $collaborator['cpf'] ?></td>
                                <td><?= $collaborator['email'] ?></td>
                                <td><i class="fas fa-trash text-danger" onclick="deletar(<?= $collaborator['id'] ?>)"></i></td>
                                <td><i class="fas fa-edit text-info"></i></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->

        </div>
        <!-- /.card -->
    </div>
</div>

<script>
    function deletar(id){
        location.href = '/colaborador/listar/deletar?id=' + id;
    }
</script>