<?php if(isset($_GET['save']) && $_GET['save'] == 1){ ?>
    <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h5><i class="icon fas fa-check"></i> Sucesso!</h5>
        Colaborador cadastrado com sucesso.
    </div>
<?php } ?>

<?php if(isset($_GET['save']) && $_GET['save'] == 2){ ?>
    <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h5><i class="icon fas fa-check"></i> Erro!</h5>
        Erro ao cadastra colaborador.
    </div>
<?php } ?>

<div class="card card-primary">
    <div class="card-header">
        <h4>Cadastro colaborador</h4>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form action="/colaborador/cadastrar/save" method="post">
        <div class="card-body">
            <div class="form-group">
                <label for="exampleInputEmail1">Nome completo</label>
                <input type="text" name="nome" class="form-control" id="InputNome" placeholder="Enter nome"
                    required maxlength="50">
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Telefone</label>
                <input type="tel" name="telefone" class="form-control" id="InputTelefone" placeholder="(00) 00000-0000"
                    required maxlength="15">
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">CPF</label>
                <input type="text" name="cpf" class="form-control" id="InputCpf" placeholder="000.000.000-00"
                    required maxlength="14">
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">E-mail</label>
                <input type="email" name="email" class="form-control" id="InputEmail" placeholder="Enter e-mail"
                    required maxlength="100">
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Senha</label>
                <input type="password" name="senha" class="form-control" id="InputSenha" placeholder="Enter password"
                    required minlength="8" maxlength="32">
            </div>

        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
    </form>
</div>