<li class="nav-item">
    <a href="/home" class="nav-link">
        <i class="nav-icon fas fa-home"></i>
        <p>Home</p>
    </a>
</li>

<li class="nav-item">
    <a href="#" class="nav-link">
        <i class="nav-icon fab fa-buromobelexperte"></i>
        <p>
            Categoria
            <i class="right fas fa-angle-left"></i>
        </p>
    </a>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="/categoria/cadastrar" class="nav-link">
                <i class="nav-icon fas fa-plus-square"></i>
                <p>Cadastrar</p>
            </a>
        </li>
    </ul>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="/categoria/listar" class="nav-link">
                <i class="nav-icon fas fa-list"></i>
                <p>Listar</p>
            </a>
        </li>
    </ul>
</li>

<li class="nav-item">
    <a href="#" class="nav-link">
        <i class="nav-icon fas fa-truck-loading"></i>
        <p>
            Fornecedor
            <i class="right fas fa-angle-left"></i>
        </p>
    </a>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="/fornecedor/cadastrar" class="nav-link">
                <i class="nav-icon fas fa-plus-square"></i>
                <p>Cadastrar</p>
            </a>
        </li>
    </ul>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="/fornecedor/listar" class="nav-link">
                <i class="nav-icon fas fa-list"></i>
                <p>Listar</p>
            </a>
        </li>
    </ul>
</li>

<li class="nav-item">
    <a href="#" class="nav-link">
        <i class="nav-icon fas fa-stopwatch"></i>
        <p>
            Serviço
            <i class="right fas fa-angle-left"></i>
        </p>
    </a>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="/servico/cadastrar" class="nav-link">
                <i class="nav-icon fas fa-plus-square"></i>
                <p>Cadastrar</p>
            </a>
        </li>
    </ul>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="/servico/listar" class="nav-link">
                <i class="nav-icon fas fa-list"></i>
                <p>Listar</p>
            </a>
        </li>
    </ul>
</li>

<li class="nav-item">
    <a href="#" class="nav-link">
        <i class="nav-icon fas fa-box-open"></i>
        <p>
            Produto
            <i class="right fas fa-angle-left"></i>
        </p>
    </a>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="/produto/cadastrar" class="nav-link">
                <i class="nav-icon fas fa-plus-square"></i>
                <p>Cadastrar</p>
            </a>
        </li>
    </ul>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="/produto/listar" class="nav-link">
                <i class="nav-icon fas fa-list"></i>
                <p>Listar</p>
            </a>
        </li>
    </ul>
</li>

<li class="nav-item">
    <a href="#" class="nav-link">
        <i class="nav-icon fas fa-users"></i>
        <p>
            Colaborador
            <i class="right fas fa-angle-left"></i>
        </p>
    </a>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="/colaborador/cadastrar" class="nav-link">
                <i class="nav-icon fas fa-plus-square"></i>
                <p>Cadastrar</p>
            </a>
        </li>
    </ul>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="/colaborador/listar" class="nav-link">
                <i class="nav-icon fas fa-list"></i>
                <p>Listar</p>
            </a>
        </li>
    </ul>
</li>