<li class="nav-item">
    <a href="/home" class="nav-link">
        <i class="nav-icon fas fa-chart-pie"></i>
        <p>Home</p>
    </a>
</li>

<li class="nav-item">
    <a href="/categoria" class="nav-link">
        <i class="nav-icon fas fa-chart-pie"></i>
        <p>
            Categoria
        </p>
    </a>
</li>

<li class="nav-item">
    <a href="/fornecedor" class="nav-link">
        <i class="nav-icon fas fa-chart-pie"></i>
        <p>
            Fornecedor
        </p>
    </a>
</li>

<li class="nav-item">
    <a href="/servico" class="nav-link">
        <i class="nav-icon fas fa-chart-pie"></i>
        <p>
            Serviço
        </p>
    </a>
</li>

<li class="nav-item">
    <a href="/produto" class="nav-link">
        <i class="nav-icon fas fa-chart-pie"></i>
        <p>
            Produto
        </p>
    </a>
</li>

<li class="nav-item">
    <a href="#" class="nav-link">
        <i class="nav-icon fas fa-chart-pie"></i>
        <p>
            Colaborador
            <i class="right fas fa-angle-left"></i>
        </p>
    </a>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="/colaborador/cadastrar" class="nav-link">
                <i class="nav-icon fas fa-chart-pie"></i>
                <p>Cadastrar</p>
            </a>
        </li>
    </ul>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="/colaborador/listar" class="nav-link">
                <i class="nav-icon fas fa-chart-pie"></i>
                <p>Listar</p>
            </a>
        </li>
    </ul>
</li>

<!--
<li class="nav-item">
    <a href="#" class="nav-link">
        <i class="nav-icon fas fa-chart-pie"></i>
        <p>
            Categoria
            <i class="right fas fa-angle-left"></i>
        </p>
    </a>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="/categoria/listagem" class="nav-link">
                <i class="nav-icon fas fa-chart-pie"></i>
                <p>Listagem</p>
            </a>
        </li>
    </ul>
</li>
-->

<!--
<li class="nav-item">
    <a href="#" class="nav-link">
        <i class="nav-icon fas fa-chart-pie"></i>
        <p>
            Configurações
            <i class="right fas fa-angle-left"></i>
        </p>
    </a>

    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="/categoria" class="nav-link">
                <i class="nav-icon fas fa-chart-pie"></i>
                <p>Categoria</p>
            </a>
        </li>
    </ul>

    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="/fornecedor" class="nav-link">
                <i class="nav-icon fas fa-chart-pie"></i>
                <p>Fornecedor</p>
            </a>
        </li>
    </ul>

    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="/servico" class="nav-link">
                <i class="nav-icon fas fa-chart-pie"></i>
                <p>Serviço</p>
            </a>
        </li>
    </ul>

    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="/produto" class="nav-link">
                <i class="nav-icon fas fa-chart-pie"></i>
                <p>Produto</p>
            </a>
        </li>
    </ul>

</li>
-->
