<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title"></h3>

                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <?php if(isset($_GET['deletar']) && $_GET['deletar'] == 1){ ?>
                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h5><i class="icon fas fa-check"></i> Sucesso!</h5>
                    Serviço excluido com sucesso.
                </div>
            <?php } ?>

            <?php if(isset($_GET['deletar']) && $_GET['deletar'] == 2) { ?>
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h5><i class="icon fas fa-check"></i> Erro!</h5>
                    Erro ao excluir serviço.
                </div>
            <?php } ?>

            <!-- /.card-header -->
            <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nome</th>
                            <th>Valor</th>
                            <th>Comissão</th>
                            <th>Status</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->view->dados as $key=>$service) { ?>
                        <tr>
                            <td><?= $service['id'] ?></td>
                            <td><?= $service['nome'] ?></td>
                            <td><?= $service['valor'] ?></td>
                            <td><?= $service['comissao'] ?></td>
                            <td><?= $service['id_status'] ?></td>
                            <td><i class="fas fa-trash text-danger" onclick="deletar(<?= $service['id'] ?>)"></i></td>
                            <td><i class="fas fa-edit text-info" onclick="editar(<?= $service['id'] ?>)"></i></td>
                        </tr>
                        <?php } ?>

                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->

        </div>
        <!-- /.card -->
    </div>
</div>

<script>
    function deletar(id) {
        location.href = '/servico/deletar?id=' + id;
    }

    function editar(id){
        location.href = '/servico/editar?id=' + id;
    }
</script>