<?php if(isset($_GET['save']) && $_GET['save'] == true){ ?>
    <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h5><i class="icon fas fa-check"></i> Sucesso!</h5>
        Categoria cadastrada com sucesso.
    </div>
<?php } ?>

<div class="card card-primary">
    <div class="card-header">
        <h4>Cadastro categoria</h4>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form action="/saveCategory" method="post">
        <div class="card-body">
            <div class="form-group">
                <label for="exampleInputEmail1">Nome</label>
                <input type="text" name="nome" class="form-control" id="exampleInputNome" placeholder="Enter nome" required maxlength="50">
            </div>
        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
    </form>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title"></h3>

                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <?php if(isset($_GET['delet']) && $_GET['delet'] == 1){ ?>

                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h5><i class="icon fas fa-check"></i> Sucesso!</h5>
                    Categoria excluida com sucesso.
                </div>
            <?php } ?>

            <?php if(isset($_GET['delet']) && $_GET['delet'] == 2) { ?>
            
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h5><i class="icon fas fa-check"></i> Erro!</h5>
                    Erro ao excluir categoria.
                </div>

            <?php } ?>

            
            

            <!-- /.card-header -->
            <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nome</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>

                        <?php foreach($this->view->dados as $indice=>$categoria){ ?>
                            <tr>
                                <td><?= $categoria['id'] ?></td>
                                <td><?= $categoria['nome'] ?></td>
                                <td><i class="fas fa-trash text-danger" onclick="deletar(<?= $categoria['id'] ?>)"></i></td>
                                <td><i class="fas fa-edit text-info"></i></td>
                            </tr>
                        <?php } ?>

                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
</div>

<script>

    function deletar(id){
        location.href = '/deleteCategory?del=' + id;
    }
</script>