<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title"></h3>
                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Search">
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <?php if(isset($_GET['delet']) && $_GET['delet'] == 1){ ?>
                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h5><i class="icon fas fa-check"></i> Sucesso!</h5>
                    Categoria excluida com sucesso.
                </div>
            <?php } ?>

            <?php if(isset($_GET['delet']) && $_GET['delet'] == 2) { ?>
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h5><i class="icon fas fa-check"></i> Erro!</h5>
                    Erro ao excluir categoria.
                </div>
            <?php } ?>

            <?php if(isset($_GET['edit']) && $_GET['edit'] == 1){ ?>
                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h5><i class="icon fas fa-check"></i> Sucesso!</h5>
                    Categoria atualizada com sucesso.
                </div>
            <?php } ?>

            <?php if(isset($_GET['edit']) && $_GET['edit'] == 2){ ?>
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h5><i class="icon fas fa-check"></i> Erro!</h5>
                    Erro ao atualizar categoria.
                </div>
            <?php } ?>

            <!-- /.card-header -->
            <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nome</th>
                            <th>Status</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->view->dados as $indice=>$categoria){ ?>
                            <tr>
                                <td><?= $categoria['id'] ?></td>
                                <td><?= $categoria['nome'] ?></td>
                                <td><?= $categoria['id_status'] ?></td>
                                <td><i class="fas fa-trash text-danger" onclick="deletar(<?= $categoria['id'] ?>)"></i></td>
                                <td><i class="fas fa-edit text-info"
                                        onclick="editar(<?= $categoria['id']?>)"></i></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
</div>

<script>
    function deletar(id) {
        location.href = '/deleteCategory?del=' + id;
    }

    function editar(id) {
        location.href = '//categoria/editar?id=' + id;
    }
</script>