<?php
    if(isset($this->view->dados['id']) && $this->view->dados['id'] != ''){
        $titulo = 'Editar fornecedor';
        $url = '/fornecedor/editar/atualizar';
        $value = $this->view->dados['nome'];
        $id = $this->view->dados['id'];

    } else {
        $titulo = 'Cadastro fornecedor';
        $url = '/fornecedor/save';
        $value = '';
    }
?>

<?php if(isset($_GET['save']) && $_GET['save'] == 1){ ?>
    <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h5><i class="icon fas fa-check"></i> Sucesso!</h5>
        Fornecedor cadastrado com sucesso.
    </div>
<?php } ?>

<?php if(isset($_GET['save']) && $_GET['save'] == 2){ ?>
    <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h5><i class="icon fas fa-check"></i> Erro!</h5>
        Erro ao cadastra fornecedor.
    </div>
<?php } ?>

<div class="card card-primary">
    <div class="card-header">
        <h4><?= $titulo ?></h4>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form action="<?= $url ?>" method="post">
        <div class="card-body">
            <div class="form-group">
                <label for="exampleInputEmail1">Nome</label>
                <input value="<?= $value ?>" type="text" name="nome" class="form-control" id="exampleInputNome" placeholder="Enter nome"
                    required maxlength="50">
            </div>
            <?php if(isset($this->view->dados['id']) && $this->view->dados['id'] != ''){ ?>
                <div hidden class="form-group">
                    <input value="<?= $id ?>" type="text" name="id">
                </div>
            <?php } ?>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
    </form>
</div>